### PR TITLE
Add Angular

### PR DESCRIPTION
**Pull request by kamilkisiela**

### CODE REVIEW

**Comment by fetis** [comment]
any update on this? would be nice to have Angular in docs as well

**Comment by tlaverdure** [comment]
Please merge, it is really confusing that this part of the documentation is not in the navigation.

**Comment by trevorblades** [comment]
At this time, we're only showing projects officially supported by Apollo in the main nav. We do have Apollo Angular listed in the [View integrations](https://www.apollographql.com/docs/react/integrations/integrations) page in the docs though!

**Comment by matt-senseye** [comment]
My feedback as a user of Apollo-Angular is that this makes things quite confusing when getting started. I realise that React is the officially supported platform but given Apollo Client's broader reach this does impact the perception of Apollo for those of us using the other integrations.

Regarding the "View Integrations" page, it is good that Angular and the other integrations are listed but that page is fairly hard to discover because that page lives within the `Apollo Client (React)` docs. It seems unlikely that users of Angular, Vue, Svelte etc. would know to dig through the React docs to find these links.

Perhaps one option to consider is to keep the main nav focussed on core projects but provide a more obvious link to the list of third-party integrations in the main nav somewhere (for example, this spot in the screenshot below)?

Screenshot 2020-08-13 at 13 12 50

**Pull request closed without merging**
